# docker-compose.yml
version: '3.8'

services:
  user-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s